[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_nft_anchor ="F72tM7HzRFdKHbRAjTkWPD3QHgMUSoY8xX9RzvrU7zS9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ackermann/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
